apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-soat-categorias-config
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-categorias
data:
  NODE_ENV: "production"
  PORT: "3000"
  AWS_REGION: "us-east-1"
  
  # Database Configuration
  DATABASE_HOST: "fiap-soat-db-categorias.cjq57yoxrulq.us-east-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "fiapdb_categorias"
  DATABASE_USERNAME: "postgresadmin"
  DATABASE_SSL: "true"
