apiVersion: v1
kind: Secret
metadata:
  name: fiap-soat-categorias-secrets
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-categorias
type: Opaque
stringData:
  # Database Password
  # Substituir pelo valor real antes do deploy
  DATABASE_PASSWORD: "your-database-password-here"
