apiVersion: v1
kind: Service
metadata:
  name: fiap-soat-categorias-service
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-categorias
    service: categorias
spec:
  type: LoadBalancer
  selector:
    app: fiap-soat-categorias
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
